### ISSUE TITLE
shield expects a globally installed jpm

### ISSUE THREAD

**Issue by pdehaan** [gregglind/shield-study-cli#15]
... I see it in the prerequisite global CLI tools (along w/ **shield-study-cli**), but it'd be nice if we could find a solution for using the locally installed jpm instead of requiring a global one (since global dependencies are 👎 ).

``` sh
$ ../node_modules/.bin/shield --version # 1.2.2
$ ../node_modules/.bin/shield run . -- -b Aurora

shield [INFO] --prefs:
{}
shield [INFO] choosing variation at random
shield [INFO] firstrun: simulate firstrun as NOW
shield [INFO] combined prefs: /var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/ea393a81-7787-4087-9519-2a6a2bbe8a3b.json
{
  "toolkit.telemetry.enabled": "false",
  "browser.selfsuppport.enabled": false,
  "general.warnOnAboutConfig": false
}
shield [INFO] jpm args:
[ 'jpm',
  'run',
  '--addon-dir',
  '.',
  '--prefs',
  '/var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/ea393a81-7787-4087-9519-2a6a2bbe8a3b.json',
  '-b',
  'Aurora' ]
/Users/pdehaan/dev/tmp/del/shield-cli-test/node_modules/shield-study-cli/node_modules/shelljs-nodecli/lib/shelljs-nodecli.js:104
            throw new Error("Couldn't find " + name + ".");
            ^

Error: Couldn't find jpm.
    at Object.exec (/Users/pdehaan/dev/tmp/del/shield-cli-test/node_modules/shield-study-cli/node_modules/shelljs-nodecli/lib/shelljs-nodecli.js:104:19)
    at Command.<anonymous> (/Users/pdehaan/dev/tmp/del/shield-cli-test/node_modules/shield-study-cli/index.js:157:18)
    at Command.listener (/Users/pdehaan/dev/tmp/del/shield-cli-test/node_modules/shield-study-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/pdehaan/dev/tmp/del/shield-cli-test/node_modules/shield-study-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/pdehaan/dev/tmp/del/shield-cli-test/node_modules/shield-study-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/pdehaan/dev/tmp/del/shield-cli-test/node_modules/shield-study-cli/index.js:218:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

**Comment by gregglind** [comment]
I claim it actually doesn't require a global one, per "node-shelljs", but it _prefers_ one.  I also agree that it should be the reverse... preferring the local one to global.  Easy fix is to make the path explicit in the call.

**Comment by pdehaan** [comment]
> I claim it actually doesn't require a global one, per "node-shelljs", but it prefers one.

The fact I don't have a globally installed **jpm** and it failed, would make me think it more than prefers it.

**Comment by gregglind** [comment]
I am unable to verify this.  
1.  I uninstalled global jpm.  
2.  added a line to index.js

`console.info("jpm path:", nodeCLI.getPath('jpm'))`

And it seems to work fine.  

Something is missing here :)

**Comment by gregglind** [comment]
I have looked into this again, and as of 1.2.2 I cannot figure out how to reproduce.

I tried
- uninstalling global jpm
- adding `getPath` debugging
- unlinking shield as a global

However, I am still going to just hard code the path, and get over myself :)

**Comment by gregglind** [comment]
@pdehaan, I know this old news, BUT do you claim it should use SHIELD's copy of JPM or the addon-dir's copy of `jpm`?  I am finally able to reproduce this, and am going to fix it so that the shield copy of jpm is used.

ALSO, i know jpm is dead soon, and will work on making this tool work with extensions.

Thanks!

GL
