### ISSUE TITLE
Unable to install? Path must be a string. Received undefined

### ISSUE THREAD

**Issue by groovecoder** [gregglind/shield-study-cli#22]
```
MacBook-Pro:code lcrouch$ npm i -g shield-study-cli jpm

> shield-study-cli@1.3.0 prepublish /Users/lcrouch/code/shield-study-cli
> npm shrinkwrap

npm WARN shrinkwrap Excluding devDependency: addons-linter@0.15.3 {}
npm WARN shrinkwrap Excluding devDependency: dispensary@0.7.0 {}
npm WARN shrinkwrap Excluding devDependency: npm@3.10.3 {}
npm WARN shrinkwrap Excluding devDependency: standard@7.1.2 {}
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/lcrouch/.nvm/versions/node/v6.3.1/bin/node" "/Users/lcrouch/.nvm/versions/node/v6.3.1/bin/npm" "shrinkwrap"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! Path must be a string. Received undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lcrouch/code/shield-study-cli/npm-debug.log

npm ERR! addLocal Could not install /Users/lcrouch/code/shield-study-cli
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/lcrouch/.nvm/versions/node/v6.3.1/bin/node" "/Users/lcrouch/.nvm/versions/node/v6.3.1/bin/npm" "i" "-g" "shield-study-cli" "jpm"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! shield-study-cli@1.3.0 prepublish: `npm shrinkwrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shield-study-cli@1.3.0 prepublish script 'npm shrinkwrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shield-study-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm shrinkwrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shield-study-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls shield-study-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lcrouch/code/npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/lcrouch/.nvm/versions/node/v6.3.1/bin/node',
1 verbose cli   '/Users/lcrouch/.nvm/versions/node/v6.3.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'shield-study-cli',
1 verbose cli   'jpm' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData shield-study-cli
8 silly fetchPackageMetaData jpm
9 silly fetchNamedPackageData jpm
10 silly mapToRegistry name jpm
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'jpm',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'jpm',
13 silly mapToRegistry   name: 'jpm',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/jpm
15 silly fetchDirectoryPackageData shield-study-cli
16 verbose request uri https://registry.npmjs.org/jpm
17 verbose request no auth needed
18 info attempt registry request try #1 at 11:11:13 AM
19 verbose request id d9ce5e5e0928ecf2
20 verbose etag "59JC9SJC0O0SKZ5RLEDMCR4D3"
21 http request GET https://registry.npmjs.org/jpm
22 http 304 https://registry.npmjs.org/jpm
23 verbose headers { date: 'Wed, 19 Oct 2016 16:11:13 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   'cache-control': 'max-age=300',
23 verbose headers   etag: '"59JC9SJC0O0SKZ5RLEDMCR4D3"',
23 verbose headers   age: '0',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-dfw1822-DFW',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1476893473.402363,VS0,VE261',
23 verbose headers   vary: 'Accept-Encoding' }
24 silly get cb [ 304,
24 silly get   { date: 'Wed, 19 Oct 2016 16:11:13 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=300',
24 silly get     etag: '"59JC9SJC0O0SKZ5RLEDMCR4D3"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-dfw1822-DFW',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1476893473.402363,VS0,VE261',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose etag https://registry.npmjs.org/jpm from cache
26 verbose get saving jpm to /Users/lcrouch/.npm/registry.npmjs.org/jpm/.cache.json
27 verbose correctMkdir /Users/lcrouch/.npm correctMkdir not in flight; initializing
28 silly install normalizeTree
29 silly loadCurrentTree Finishing
30 silly loadIdealTree Starting
31 silly install loadIdealTree
32 silly cloneCurrentTree Starting
33 silly install cloneCurrentTreeToIdealTree
34 silly cloneCurrentTree Finishing
35 silly loadShrinkwrap Starting
36 silly install loadShrinkwrap
37 silly loadShrinkwrap Finishing
38 silly loadAllDepsIntoIdealTree Starting
39 silly install loadAllDepsIntoIdealTree
40 silly resolveWithNewModule shield-study-cli@1.3.0 checking installable status
41 silly cache add args [ 'shield-study-cli', null ]
42 verbose cache add spec shield-study-cli
43 silly resolveWithNewModule jpm@1.2.2 checking installable status
44 silly cache add args [ 'jpm', null ]
45 verbose cache add spec jpm
46 silly cache add parsed spec Result {
46 silly cache add   raw: 'jpm',
46 silly cache add   scope: null,
46 silly cache add   escapedName: 'jpm',
46 silly cache add   name: 'jpm',
46 silly cache add   rawSpec: '',
46 silly cache add   spec: 'latest',
46 silly cache add   type: 'tag' }
47 silly addNamed jpm@latest
48 verbose addNamed "latest" is being treated as a dist-tag for jpm
49 info addNameTag [ 'jpm', 'latest' ]
50 silly mapToRegistry name jpm
51 silly mapToRegistry using default registry
52 silly mapToRegistry registry https://registry.npmjs.org/
53 silly mapToRegistry data Result {
53 silly mapToRegistry   raw: 'jpm',
53 silly mapToRegistry   scope: null,
53 silly mapToRegistry   escapedName: 'jpm',
53 silly mapToRegistry   name: 'jpm',
53 silly mapToRegistry   rawSpec: '',
53 silly mapToRegistry   spec: 'latest',
53 silly mapToRegistry   type: 'tag' }
54 silly mapToRegistry uri https://registry.npmjs.org/jpm
55 verbose addNameTag registry:https://registry.npmjs.org/jpm not in flight; fetching
56 silly cache add parsed spec Result {
56 silly cache add   raw: 'shield-study-cli',
56 silly cache add   scope: null,
56 silly cache add   escapedName: 'shield-study-cli',
56 silly cache add   name: null,
56 silly cache add   rawSpec: 'shield-study-cli',
56 silly cache add   spec: '/Users/lcrouch/code/shield-study-cli',
56 silly cache add   type: 'directory' }
57 verbose get https://registry.npmjs.org/jpm not expired, no request
58 silly addNameTag next cb for jpm with tag latest
59 silly addNamed jpm@1.2.2
60 verbose addNamed "1.2.2" is a plain semver version for jpm
61 silly cache afterAdd jpm@1.2.2
62 verbose afterAdd /Users/lcrouch/.npm/jpm/1.2.2/package/package.json not in flight; writing
63 verbose correctMkdir /Users/lcrouch/.npm correctMkdir not in flight; initializing
64 verbose addLocalDirectory /Users/lcrouch/.npm/shield-study-cli/1.3.0/package.tgz not in flight; packing
65 verbose correctMkdir /Users/lcrouch/.npm correctMkdir not in flight; initializing
66 info lifecycle shield-study-cli@1.3.0~prepublish: shield-study-cli@1.3.0
67 verbose lifecycle shield-study-cli@1.3.0~prepublish: unsafe-perm in lifecycle true
68 verbose lifecycle shield-study-cli@1.3.0~prepublish: PATH: /Users/lcrouch/.nvm/versions/node/v6.3.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/lcrouch/code/shield-study-cli/node_modules/.bin:/Users/lcrouch/.nvm/versions/node/v6.3.1/bin:/Users/lcrouch/.nvm/versions/node/v6.3.1/bin:/Users/lcrouch/anaconda/bin:/Users/lcrouch/.rvm/gems/ruby-2.0.0-p247/bin:/Users/lcrouch/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/lcrouch/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/lcrouch/.rvm/bin:/Users/lcrouch/.rvm/bin:/Users/lcrouch/code/moz-git-tools:/usr/local/heroku/bin:./node_module/.bin:/Users/lcrouch/go/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/opengeo/pgsql/9.1/bin:/Users/lcrouch/bin:/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin:/usr/local/git/bin/git-tools:/Users/lcrouch/adt-bundle-mac/sdk/tools:/Users/lcrouch/adt-bundle-mac/sdk/build-tools:/Users/lcrouch/adt-bundle-mac/sdk/platform-tools
69 verbose lifecycle shield-study-cli@1.3.0~prepublish: CWD: /Users/lcrouch/code/shield-study-cli
70 silly lifecycle shield-study-cli@1.3.0~prepublish: Args: [ '-c', 'npm shrinkwrap' ]
71 verbose afterAdd /Users/lcrouch/.npm/jpm/1.2.2/package/package.json written
72 silly lifecycle shield-study-cli@1.3.0~prepublish: Returned: code: 1  signal: null
73 info lifecycle shield-study-cli@1.3.0~prepublish: Failed to exec prepublish script
74 error addLocal Could not install /Users/lcrouch/code/shield-study-cli
75 silly rollbackFailedOptional Starting
76 silly rollbackFailedOptional Finishing
77 silly runTopLevelLifecycles Starting
78 silly runTopLevelLifecycles Finishing
79 silly install printInstalled
80 verbose stack Error: shield-study-cli@1.3.0 prepublish: `npm shrinkwrap`
80 verbose stack Exit status 1
80 verbose stack     at EventEmitter.<anonymous> (/Users/lcrouch/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
80 verbose stack     at emitTwo (events.js:106:13)
80 verbose stack     at EventEmitter.emit (events.js:191:7)
80 verbose stack     at ChildProcess.<anonymous> (/Users/lcrouch/.nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
80 verbose stack     at emitTwo (events.js:106:13)
80 verbose stack     at ChildProcess.emit (events.js:191:7)
80 verbose stack     at maybeClose (internal/child_process.js:852:16)
80 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
81 verbose pkgid shield-study-cli@1.3.0
82 verbose cwd /Users/lcrouch/code
83 error Darwin 15.6.0
84 error argv "/Users/lcrouch/.nvm/versions/node/v6.3.1/bin/node" "/Users/lcrouch/.nvm/versions/node/v6.3.1/bin/npm" "i" "-g" "shield-study-cli" "jpm"
85 error node v6.3.1
86 error npm  v3.10.3
87 error code ELIFECYCLE
88 error shield-study-cli@1.3.0 prepublish: `npm shrinkwrap`
88 error Exit status 1
89 error Failed at the shield-study-cli@1.3.0 prepublish script 'npm shrinkwrap'.
89 error Make sure you have the latest version of node.js and npm installed.
89 error If you do, this is most likely a problem with the shield-study-cli package,
89 error not with npm itself.
89 error Tell the author that this fails on your system:
89 error     npm shrinkwrap
89 error You can get information on how to open an issue for this project with:
89 error     npm bugs shield-study-cli
89 error Or if that isn't available, you can get their info via:
89 error     npm owner ls shield-study-cli
89 error There is likely additional logging output above.
90 verbose exit [ 1, true ]
```

**Comment by groovecoder** [comment]
I used `nvm` to install LTS (`4.6.1`) and latest (`6.9.0`). I was able to install `shield-study-cli` on both those versions.
