### ISSUE TITLE
Error: Cannot find module 'clim'

### ISSUE THREAD

**Issue by groovecoder** [gregglind/shield-study-cli#5]
In `shield-study-cli@1.2.0`, `clim` is a dependency, not just a dev dependency.

```
$ shield run . -- -b Aurora
module.js:442
    throw err;
    ^

Error: Cannot find module 'clim'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lcrouch/.nvm/versions/node/v6.3.1/lib/node_modules/shield-study-cli/index.js:13:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by groovecoder** [comment]
Fixed in https://github.com/gregglind/shield-study-cli/commit/c81f1ac5732b402e23ccfaadd4b9a77ec608dfaa
